export default function Data() {
    return [
            {name: "Arsenal", id: 57},
            {name: "Aston Villa", id: 58},
            {name: "Chelsea", id: 61},
            {name: "Everton", id: 62},
            {name: "Liverpool", id: 64},
            {name: "Manchester City", id: 65},
            {name: "Manchester United", id: 66},
            {name: "Newcastle United", id: 67},
            {name: "Norwich City", id: 68},
            {name: "Tottenham Hotspurs", id: 73},
            {name: "Wolverhampton Wanderers", id: 76},
            {name: "Burnley", id: 328},
            {name: "Leicester City", id: 338},
            {name: "Southhampton", id: 340},
            {name: "Watford City", id: 346},
            {name: "Crystal Palace", id: 354},
            {name: "Sheffield United", id: 356},
            {name: "Brighton & Hove Albion", id: 397},
            {name: "West Ham United", id: 563},
            {name: "AFC Bournemouth", id: 1044},  
        ]
    }
            // "Champions League" : 2001, teams2: {
            //     id: 3, name: "Bayer 04 Leverkusen",
            //     id: 4, name: "BV Borussia 09 Dortmund",
            //     id: 5, name: "FC Bayern München",
            //     id: 61, name: "Chelsea FC",
            //     id: 64, name: "Liverpool FC",
            //     id: 65, name: "Manchester City FC",
            //     id: 73, name: "Tottenham Hotspur FC",
            //     id: 78, name: "Club Atlético de Madrid",
            //     id: 81, name: "FC Barcelona",
            //     id: 86, name: "Real Madrid CF",
            //     id: 95, name: "Valencia CF",
            //     id: 102, name: "Atalanta BC",
            //     id: 108, name: "FC Internazionale Milano",
            //     id: 109, name: "Juventus FC",
            //     id: 113, name: "SSC Napoli",
            //     id: 503, name: "FC Porto", 
            //     id: 521, name: "Lille OSC", 
            //     id: 523, name: "Olympique Lyonnais", 
            //     id: 524, name: "Paris Saint-Germain FC", 
            //     id: 610, name: "Galatasaray SK",
            //     id: 611, name: "Qarabağ Ağdam FK", 
            //     id: 654, name: "PAE Olympiakos SFP",
            //     id: 674, name: "PSV",
            //     id: 678, name: "AFC Ajax",
            //     id: 721, name: "RB Leipzig",
            //     id: 729, name: "FC Basel 1893",
            //     id: 731, name: "FK Zenit Sankt-Petersburg", 
            //     id: 732, name: "Celtic FC",
            //     id: 734, name: "NK Maribor", 
            //     id: 748, name: "FK BATE Borisov", 
            //     id: 752, name: "APOEL FC", 
            //     id: 755, name: "GNK Dinamo Zagreb", 
            //     id: 842, name: "FK Dynamo Kyiv",
            //     id: 851, name: "Club Brugge KV",
            //     id: 889, name: "Rosenborg BK", 
            //     id: 930, name: "SK Slavia Praha", 
            //     id: 1858, name: "KRC Genk", 
            //     id: 1871, name: "BSC Young Boys",
            //     id: 1873, name: "Dundalk FC", 
            //     id: 1875, name: "F91 Diddeleng", 
            //     id: 1876, name: "FC København", 
            //     id: 1877, name: "FC Red Bull Salzburg",
            //     id: 1879, name: "FC Santa Coloma",
            //     id: 1880, name: "FC Sheriff Tiraspol", 
            //     id: 1881, name: "FC Viktoria Plzeň",
            //     id: 1884, name: "Astana FK", 
            //     id: 1887, name: "FK Shakhtar Donetsk", 
            //     id: 1896, name: "Linfield FC",
            //     id: 1897, name: "Medipol Başakşehir FK",
            //     id: 1901, name: "PFK Ludogorets 1945 Razgrad",
            //     id: 1903, name: "Sport Lisboa e Benfica",
            //     id: 1904, name: "The New Saints FC",
            //     id: 2016, name: "LASK Linz",  
            //     id: 4275, name: "FK Sarajevo",
            //     id: 5106, name: "Nõmme Kalju FC",
            //     id: 5123, name: "Helsingin JK",
            //     id: 5277, name: "AIK Fotboll", 
            //     id: 5452, name: "FK Krasnodar",  
            //     id: 5455, name: "FK Lokomotiv Moskva",
            //     id: 5515, name: "FC CFR 1907 Cluj", 
            //     id: 5628, name: "GKS Piast Gliwice", 
            //     id: 5813, name: "Valletta FC", 
            //     id: 5819, name: "FK Sūduva Marijampolė",
            //     id: 5826, name: "Rīga FC", 
            //     id: 5929, name: "Maccabi Tel Aviv FC", 
            //     id: 5945, name: "KF Valur",
            //     id: 5954, name: "Ferencvárosi TC", 
            //     id: 6146, name: "PAOK FC", 
            //     id: 7281, name: "Lincoln Red Imps FC", 
            //     id: 7283, name: "FK Crvena Zvezda",
            //     id: 7284, name: "FK Sutjeska Nikšić", 
            //     id: 7285, name: "KF Shkëndija 79",
            //     id: 7492, name: "FK Partizani",  
            //     id: 7509, name: "ŠK Slovan Bratislava",
            //     id: 8101, name: "KF Feronikeli", 
            //     id: 8102, name: "SP Tre Penne",
            //     id: 8164, name: "FC Ararat-Armenia",
            //     id: 8165, name: "FC Saburtalo", 
            //     id: 8166, name: "HB",
            // }
        
